# Input/Output
ref_dir: "/home/boittier/Documents/github/MDCMfast/examples/ref"
name: "h2o"  # Base name for input files

# Molecule parameters
n_atoms: 3
lmax: 5
qtot: 0.0

# Fitting parameters
ntry: 1  # Number of tries per fit
n_fits: 1  # Number of separate fits
max_charges_per_atom: 4
min_molecular_charges: 3
max_molecular_charges: 12 