from pathlib import Path
from mdcmfast import INSTALL_DIR, determine_n_charges


# Configuration
configfile: "config.yaml"

# Define paths to executables
MTPFIT = f"{INSTALL_DIR}/src/mdcmfast/bin/mtpfit.py"
PCUBEFIT = f"{INSTALL_DIR}/src/mdcmfast/bin/pcubefit.x"
COMB_XYZ_TO_DCM = f"{INSTALL_DIR}/src/mdcmfast/bin/comb-xyz-to-dcm.pl"

name = config["name"]
charges =  determine_n_charges(config["min_molecular_charges"], config["max_molecular_charges"])
atom_num = range(1, config["n_atoms"] + 1)
print(f"Charges to fit: {charges}")
n_charges = range(config["min_molecular_charges"], config["max_molecular_charges"] + 1)
print(f"Charges per atom: {n_charges}")
print(f"Atoms: {atom_num}")

config["n_charges"] = n_charges
config["atom_num"] = atom_num


# Default target rule
rule all:
    input:
        expand(f"{INSTALL_DIR}/results/{{name}}/charmm/{{name}}_{{n_charges}}charges.dcm",
               name=config["name"],
               n_charges=range(config["min_molecular_charges"], 
                             config["max_molecular_charges"] + 1))

# 1. Fit atomic multipoles to reference ESP
rule fit_multipoles:
    input:
        pot_cube = config["ref_dir"] + "/{0}-pot.cube".format(config["name"]),
        dens_cube = config["ref_dir"] + "/{0}-dens.cube".format(config["name"])
    output:
        mtpl = f"{INSTALL_DIR}/results/{config['name']}/1-mtp-fit/fitted-mtpl.dat"
    params:
        lmax = config["lmax"],
        qtot = config["qtot"],
        name = config["name"]
    shell:
        """
        {MTPFIT} -pot {input.pot_cube} -dens {input.dens_cube} \
                  -lmax {params.lmax} -qtot {params.qtot}
        echo "Fitted multipoles saved to {output.mtpl}"
        cp fitted-mtpl.dat {INSTALL_DIR}/results/{params.name}/1-mtp-fit/fitted-mtpl.dat
        """

# 2. Generate and analyze cube file from fitted multipoles
rule analyze_multipoles:
    input:
        pot_cube = config["ref_dir"] + "/{0}-pot.cube".format(config["name"]),
        dens_cube = config["ref_dir"] + "/{0}-dens.cube".format(config["name"]),
        mtpl = f"{INSTALL_DIR}/results/{config['name']}/1-mtp-fit/fitted-mtpl.dat"
    output:
        cube = f"{INSTALL_DIR}/results/{config['name']}/1-mtp-fit/ditriantapole_expansion.cube",
        log = f"{INSTALL_DIR}/results/{config['name']}/1-mtp-fit/analyze-cube.log"
    shell:
        """
        # Generate cube from fitted multipoles
        {PCUBEFIT} -v -generate -multipole -esp {input.pot_cube} \
                   -dens {input.dens_cube} -mtpfile {input.mtpl}
        
        # Analyze fit quality
        {PCUBEFIT} -v -analysis -esp {input.pot_cube} \
                   -esp2 {output.cube} -dens {input.dens_cube} > {output.log}
        """

# 3. Fit atomic MDCM models
rule fit_atomic_mdcm:
    input:
        pot_cube = config["ref_dir"] + "/{0}-pot.cube".format(config["name"]),
        dens_cube = config["ref_dir"] + "/{0}-dens.cube".format(config["name"]),
        mtpl = f"{INSTALL_DIR}/results/{config['name']}/1-mtp-fit/fitted-mtpl.dat"
    output:
        xyz = f"{INSTALL_DIR}/results/{config['name']}/2-fit-atoms/multipole{{atom_num}}_{{atom_num}}charges.xyz",
        log = f"{INSTALL_DIR}/results/{config['name']}/2-fit-atoms/multipole{{atom_num}}_{{atom_num}}charges-fit.log"
    params:
        max_charges = config["max_charges_per_atom"],
        ntry = config["ntry"]
    shell:
        """
        mkdir -p $(dirname {output.xyz})
        
        {PCUBEFIT} -greedy -mtpfile {input.mtpl} \
                   -esp {input.pot_cube} -dens {input.dens_cube} \
                   -nacmin 1 -nacmax {params.max_charges} \
                   -atom {wildcards.atom_num} -ntry {params.ntry} \
                   -onlymultipoles -v > {output.log}
        """

# 4. Fit molecular MDCM model
rule fit_molecular_mdcm:
    input:
        pot_cube = config["ref_dir"] + "/{0}-pot.cube".format(config["name"]),
        dens_cube = config["ref_dir"] + "/{0}-dens.cube".format(config["name"]),
        mtpl = f"{INSTALL_DIR}/results/{config['name']}/1-mtp-fit/fitted-mtpl.dat",
        atom_fits = expand(f"{INSTALL_DIR}/results/{config['name']}/2-fit-atoms/multipole{{atom_num}}_{{atom_num}}charges.xyz",
                         atom_num=config["atom_num"])
    output:
        xyz = f"{INSTALL_DIR}/results/{config['name']}/3-fit-molecule/{config['name']}_{{n_charges}}charges.xyz",
        log = f"{INSTALL_DIR}/results/{config['name']}/3-fit-molecule/{config['name']}_{{n_charges}}charges.log"
    params:
        ntry = config["ntry"],
        max_atom_charges = config["max_charges_per_atom"]
    shell:
        """
        mkdir -p $(dirname {output.xyz})
        
        {PCUBEFIT} -greedy -esp {input.pot_cube} -dens {input.dens_cube} \
                   -mtpfile {input.mtpl} -ncmin {wildcards.n_charges} \
                   -ncmax {wildcards.n_charges} -nacmax {params.max_atom_charges} \
                   -ntry {params.ntry} -v > {output.log}
        """

# 5. Analyze final model
rule analyze_model:
    input:
        xyz = f"{INSTALL_DIR}/results/{config['name']}/3-fit-molecule/{config['name']}_{{n_charges}}charges.xyz",
        pot_cube = config["ref_dir"] + "/{0}-pot.cube".format(config["name"]),
        dens_cube = config["ref_dir"] + "/{0}-dens.cube".format(config["name"])
    output:
        cube = f"{INSTALL_DIR}/results/{config['name']}/4-analysis/{config['name']}_{{n_charges}}charges.cube",
        log = f"{INSTALL_DIR}/results/{config['name']}/4-analysis/{config['name']}_{{n_charges}}charges.log"
    shell:
        """
        # Generate cube from charge model
        {PCUBEFIT} -generate -xyz {input.xyz} -esp {input.pot_cube} \
                   -dens {input.dens_cube} -v
        
        # Analyze against reference
        {PCUBEFIT} -v -analysis -esp {input.pot_cube} \
                   -esp2 {output.cube} -dens {input.dens_cube} > {output.log}
        """

# 6. Generate CHARMM files
rule generate_charmm_files:
    input:
        xyz = f"{INSTALL_DIR}/results/{config['name']}/3-fit-molecule/{config['name']}_{{n_charges}}charges.xyz",
        dens_cube = config["ref_dir"] + "/{0}-dens.cube".format(config["name"]),
        frames = "frames.txt"
    output:
        dcm = f"{INSTALL_DIR}/results/{config['name']}/charmm/{config['name']}_{{n_charges}}charges.dcm"
    shell:
        "{COMB_XYZ_TO_DCM} {input.xyz} {input.dens_cube} {input.frames} {output.dcm}" 
